### ISSUE TITLE
Use a proxy for the streaming links 

### ISSUE THREAD

**Issue by anime-kun32** [Kiriyako/inuani#2]
Gogo anime has set cors on the streaming links 
So now have to use a proxy to be able to use the streaming links 
https://gogoanime-and-hianime-proxy.vercel.app/hls-proxy?url=video.m3u8
meaning the video sources from the api response is then attached to the URL PARAM meaning the video will play with no problem . I could have done it myself but i don't really understand your code. This is a suggestioon anyway

**Comment by Kiriyako** [comment]
Hello!

Thank you for your input.

I am aware of the CORS issue. Though I currently lack any motivation or the time to fix this site, I'll certainly look into fixing it in the future. 

Thank you :)

**Comment by anime-kun32** [comment]
The website is repairable and so I've  fixed but how do I make a pull request.

**Comment by Kiriyako** [comment]
Hello,

Thank you soo much for taking the time to fix inuani. I sincerely appreciate your efforts!! :)

**Comment by anime-kun32** [comment]
You're welcome
